### ISSUE TITLE
Excessive memory usage on a small diploid genome

### ISSUE THREAD

**Issue by fenderglass** [DecodeGenetics/Ratatosk#15] opened 2020-09-21 18:52 UTC
Hi!

I am trying to run Ratatosk on a diploid arabidopsis genome from the FALCON paper: https://www.nature.com/articles/nmeth.4035. Haploid genome size is ~140 Mb, and heterozygosity rate is ~1%. There is ~9 Gb of Illumina reads and ~22 Gb of PacBio reads.

I am using the latest github code from the master branch with all-default options (30 threads). It seems that de Bruijn graph was build successfully (with little RAM usage),  but once it begins the read correction phase, the RAM usage increases over 1.3 Tb and the process is eventually killed. Here are the last lines of the terminal output below.

Is this expected behaviour? The genome is way smaller than human, but has ~10x higher SNP rate. Any tips are appreciated!

Thanks!
Mikhail

```
Ratatosk::createPartitions(): Processed 10000 centroids.
Ratatosk::createPartitions(): Processed 10100 centroids.
Ratatosk::createPartitions(): Processed 10200 centroids.
Ratatosk::Ratatosk(): Detecting SNPs candidates (1/2).
Ratatosk::detectSNPs(): Scanning graph for k-mers with substitutions (SNPs)
Ratatosk::detectSNPs(): Number of filtered false positive candidates: 3089662
Ratatosk::Ratatosk(): Correcting long reads (1/2).
Ratatosk::correct(): Processed 1000 reads 
Ratatosk::correct(): Processed 2000 reads 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

**Comment by GuillaumeHolley** [comment] 2020-09-21 19:03
Hi @fenderglass,

Thank you for opening this issue and providing all the details. This is definitely not expected behavior but I'm not sure right now to see why this is happening. Since the correction process has started, I'm assuming that somehow, each thread happens to be storing too much information regarding the graph traversal. Since the data are in the paper, I will run it tomorrow and figure out what's going on. In the meantime. I'll keep the issue open and hopefully, I'll be in touch soon enough.

Guillaume

**Comment by fenderglass** [comment] 2020-09-22 04:05
@GuillaumeHolley thanks! Here is the link to the data just in case: https://www.ncbi.nlm.nih.gov/sra?LinkName=biosample_sra&from_uid=4539663. Illumina is easy to download, but PacBio is tricky because there are many separate runs that also need to be converted from .h5 to .fastq. To save your time, here are the converted PacBio reads that I've been using: https://drive.google.com/file/d/1ZSFHo1UFN7alktWLBlThCuqjUICT35wy/view?usp=sharing

**Comment by GuillaumeHolley** [comment] 2020-09-24 15:33
Hi @fenderglass,

Quick update: I have identified the problem and made a fix for it. It might take a few days to run some tests and make sure it does not hurt the performance but otherwise, we should be good to go :) I am currently looking at 11-12 GB of RAM for your particular input data sets.

**Comment by fenderglass** [comment] 2020-09-24 17:01
@GuillaumeHolley thanks a lot for the quick response! Hope to give it a try soon!

**Comment by GuillaumeHolley** [comment] 2020-10-05 17:21
Hi @fenderglass,

Sorry for the delay. I just pushed Ratatosk 0.3.0 which should solve your issue. Let me know if this works for you. 

Guillaume

**Comment by GuillaumeHolley** [comment] 2020-10-15 10:44
Closing the issue. Let me know if something doesn't work and I will reopen it.

**Closed by GuillaumeHolley** 2020-10-15 10:44 UTC

**Comment by fenderglass** [comment] 2020-10-16 16:36
@GuillaumeHolley thanks a lot for looking into this! Ratatosk has just finished on my dataset - seems that everything worked fine (took about 1500 CPU hours).
